services:
  postgres:
    image: postgres:17.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: 'start-dev'
    environment:
      JAVA_OPTS: -XX:UseSVE=0
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 9443
      KC_HTTP_MANAGEMENT_PORT: 9990
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
      
volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
